version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: blackjack
      POSTGRES_PASSWORD: blackjack
      POSTGRES_DB: blackjack
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blackjack"]
      interval: 5s
      timeout: 5s
      retries: 20
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: 4000
      ORIGIN: http://localhost:3000
      DATABASE_URL: postgres://blackjack:blackjack@db:5432/blackjack
      JWT_SECRET: dev_secret
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:

